#! /bin/bash
#
# Drive (xe)latex sensibly

workdir=.latexwork
engine=pdflatex
args="-interaction nonstopmode -halt-on-error -file-line-error"
dobibtex=false

while [ $# -gt 0 ] ; do
    case "$1" in
	-x) engine=xelatex ;;
	-b) dobibtex=true ;;
	-l) args="$args -papersize letter" ;;
	*) break ;;
    esac
    shift
done

if [ $# -ne 2 ] ; then
    echo >&2 "usage: latexdriver [-x] [-b] [-l] input.tex output.pdf"
    exit 1
fi

input="$1"
output="$2"

if [ ! -e "$input" ] ; then
    echo >&2 "error: input \"$input\" does not exist"
    exit 1
fi

base=$(echo "$input" |sed -e 's/\.[^.]*$//')

if [ -z "$base" ] ; then
    echo >&2 "error: failed to strip extension from input path \"$input\""
    exit 1
fi

job="$workdir/$base"
tlog="$workdir/$base.hllog" # "highlevel log"
blog="$workdir/$base.hlblg" # bibtex version thereof

mkdir -p $workdir

function logrun () {
    # $1 = command
    # $2 = boring args
    # $3 = interesting final arg
    # $4 = logfile name

    if [ -z "$2" ] ; then
	echo + $1 $3
    else
	echo + $1 ... $3
    fi

    $1 $2 $3 >&$4
    if [ $? -ne 0 ] ; then
	cat $4 >&2
	exit 1
    fi
}

logrun $engine "$args -jobname $job" $base $tlog
if $dobibtex ;then
    logrun bibtex "" $job $blog
    grep Warning $blog >&2
    # force at least one extra run:
    logrun $engine "$args -jobname $job" $base $tlog
fi

n=0

while grep -q Rerun $tlog ; do
    logrun $engine "$args -jobname $job" $base $tlog
    if [ $n -gt 10 ] ; then
	echo >&2 "error: too many iterations; check $tlog"
	exit 1
    fi
    n=$(($n + 1))
done

exec mv $job.pdf "$output"
